'use client'

import Link from 'next/link'
import { Activity, ArrowLeft, Database, LockKeyhole, RefreshCw, ShieldAlert } from 'lucide-react'

export type SurfaceKind = 'threats' | 'events' | 'audit' | 'xai' | 'continuous' | 'policies' | 'admin'

const content: Record<SurfaceKind, { eyebrow: string; title: string; description: string; icon: typeof Activity; accent: string; columns: string[] }> = {
  threats: { eyebrow: 'Security operations / threat intelligence', title: 'Threat intelligence', description: 'Monitor threat signals and response state from the connected security service.', icon: ShieldAlert, accent: 'text-rose-300', columns: ['Threat', 'Severity', 'Source', 'Target', 'Status'] },
  events: { eyebrow: 'Monitoring / security events', title: 'Security events', description: 'Review security events with explicit backend availability and severity context.', icon: Activity, accent: 'text-amber-300', columns: ['Timestamp', 'Event', 'Severity', 'Actor', 'Result'] },
  audit: { eyebrow: 'Monitoring / audit trail', title: 'Audit logs', description: 'Investigate administrative and security activity without loading unbounded records.', icon: Database, accent: 'text-cyan-300', columns: ['Timestamp', 'Action', 'Actor', 'Resource', 'Result'] },
  xai: { eyebrow: 'AI security / explainability', title: 'Explainable AI', description: 'Decision context appears here when the backend explainability service returns data.', icon: Activity, accent: 'text-violet-300', columns: ['Feature', 'Impact', 'Direction', 'Confidence'] },
  continuous: { eyebrow: 'Zero trust / continuous authentication', title: 'Continuous trust monitor', description: 'Identity, device, behavior, location, and network signals are evaluated by the connected API.', icon: LockKeyhole, accent: 'text-emerald-300', columns: ['Signal', 'Current state', 'Last evaluated', 'Risk'] },
  policies: { eyebrow: 'Zero trust / policy engine', title: 'Policy management', description: 'Active policy data is loaded from the existing FastAPI contract. No policy values are fabricated.', icon: LockKeyhole, accent: 'text-blue-300', columns: ['Policy', 'Status', 'Matches', 'Last evaluated'] },
  admin: { eyebrow: 'Privileged control plane', title: 'Administration', description: 'Protected administrative modules remain separate from the public application surface.', icon: LockKeyhole, accent: 'text-cyan-300', columns: ['Module', 'Access', 'Status', 'Last activity'] },
}

export function OperationsSurface({ kind }: { kind: SurfaceKind }) {
  const item = content[kind]
  const Icon = item.icon
  return <main className="soc-shell min-h-screen px-4 py-6 text-slate-100 sm:px-8 lg:ml-72 lg:px-10 lg:py-10"><div className="mx-auto max-w-7xl"><Link href="/dashboard" className="mb-8 inline-flex items-center gap-2 text-sm text-slate-400 transition hover:text-cyan-200"><ArrowLeft className="size-4" />Back to command center</Link><header className="mb-8 flex flex-col gap-5 border-b border-white/10 pb-8 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">{item.eyebrow}</p><h1 className="mt-3 text-balance text-4xl font-semibold tracking-tight text-white">{item.title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">{item.description}</p></div><div className={`flex size-14 items-center justify-center rounded-2xl border border-white/10 bg-white/[.04] ${item.accent}`}><Icon className="size-7" /></div></header><section className="grid gap-4 sm:grid-cols-3"><article className="soc-panel p-5"><p className="eyebrow">Service status</p><p className="mt-3 text-xl font-semibold text-amber-200">Data unavailable</p><p className="mt-2 text-xs leading-5 text-slate-500">The existing backend did not return records for this surface.</p></article><article className="soc-panel p-5"><p className="eyebrow">Data source</p><p className="mt-3 text-xl font-semibold text-cyan-200">FastAPI</p><p className="mt-2 text-xs leading-5 text-slate-500">Frontend preserves the existing API contract.</p></article><article className="soc-panel p-5"><p className="eyebrow">Integrity</p><p className="mt-3 text-xl font-semibold text-emerald-200">No simulation</p><p className="mt-2 text-xs leading-5 text-slate-500">No production security values are fabricated.</p></article></section><section className="soc-panel mt-6 overflow-hidden"><div className="flex flex-col gap-3 border-b border-white/10 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="eyebrow">Live records</p><h2 className="mt-2 text-xl font-semibold text-white">Awaiting backend response</h2></div><button type="button" className="inline-flex items-center justify-center gap-2 rounded-xl border border-white/10 px-4 py-2 text-sm text-slate-300 transition hover:border-cyan-300/30 hover:text-cyan-200"><RefreshCw className="size-4" />Refresh data</button></div><div className="overflow-x-auto"><table className="min-w-[640px] w-full text-left text-sm"><thead className="bg-white/[.03] text-xs uppercase tracking-wider text-slate-500"><tr>{item.columns.map((column) => <th className="px-5 py-4 font-semibold" key={column}>{column}</th>)}</tr></thead><tbody><tr><td colSpan={item.columns.length} className="px-5 py-16 text-center text-slate-500">No records available. Connect the backend service or try again.</td></tr></tbody></table></div></section></div></main>
}
